import { PrismaClient, Department, EmployeeStatus, EmploymentType } from '@prisma/client';

const prisma = new PrismaClient();

const AVATAR_COLORS = [
  '#6366f1', '#8b5cf6', '#ec4899', '#f59e0b', '#10b981',
  '#3b82f6', '#ef4444', '#14b8a6', '#f97316', '#84cc16',
];

// Employees with 4-level hierarchy. All dates validated against business rules:
// - DOB: 18-100 years ago (relative to 2026-08-13)
// - HireDate: >= 2000-01-01, >= DOB+18y, <= 2026-11-13 (+3 months)
const employees = [
  // ─── Level 0: CEO ───────────────────────────────────────────────────────────
  {
    id: 'emp-001',
    employeeId: 'EMP-001',
    firstName: 'Victoria',
    lastName: 'Harrington',
    email: 'victoria.harrington@acme.com',
    phone: '+12025550101',
    jobTitle: 'Chief Executive Officer',
    department: Department.OPERATIONS,
    status: EmployeeStatus.ACTIVE,
    employmentType: EmploymentType.FULL_TIME,
    hireDate: new Date('2000-03-15'),
    dateOfBirth: new Date('1972-06-10'),
    location: 'New York, NY',
    avatarColor: AVATAR_COLORS[0],
    isTopLevel: true,
    managerId: null,
    emergencyContactName: 'James Harrington',
    emergencyContactRelationship: 'Spouse',
    emergencyContactPhone: '+12025550199',
  },
  // ─── Level 1: VPs ────────────────────────────────────────────────────────────
  {
    id: 'emp-002',
    employeeId: 'EMP-002',
    firstName: 'Marcus',
    lastName: 'Chen',
    email: 'marcus.chen@acme.com',
    phone: '+14155550202',
    jobTitle: 'VP of Engineering',
    department: Department.ENGINEERING,
    status: EmployeeStatus.ACTIVE,
    employmentType: EmploymentType.FULL_TIME,
    hireDate: new Date('2002-08-01'),
    dateOfBirth: new Date('1978-02-20'),
    location: 'San Francisco, CA',
    avatarColor: AVATAR_COLORS[1],
    isTopLevel: false,
    managerId: 'emp-001',
    emergencyContactName: 'Linda Chen',
    emergencyContactRelationship: 'Spouse',
    emergencyContactPhone: '+14155550209',
  },
  {
    id: 'emp-003',
    employeeId: 'EMP-003',
    firstName: 'Sophia',
    lastName: 'Patel',
    email: 'sophia.patel@acme.com',
    phone: '+13105550303',
    jobTitle: 'VP of Product',
    department: Department.PRODUCT,
    status: EmployeeStatus.ACTIVE,
    employmentType: EmploymentType.FULL_TIME,
    hireDate: new Date('2003-01-15'),
    dateOfBirth: new Date('1980-09-05'),
    location: 'Los Angeles, CA',
    avatarColor: AVATAR_COLORS[2],
    isTopLevel: false,
    managerId: 'emp-001',
    emergencyContactName: 'Raj Patel',
    emergencyContactRelationship: 'Father',
    emergencyContactPhone: '+13105550399',
  },
  {
    id: 'emp-004',
    employeeId: 'EMP-004',
    firstName: 'Daniel',
    lastName: 'Okafor',
    email: 'daniel.okafor@acme.com',
    phone: '+17135550404',
    jobTitle: 'VP of Human Resources',
    department: Department.HR,
    status: EmployeeStatus.ACTIVE,
    employmentType: EmploymentType.FULL_TIME,
    hireDate: new Date('2001-05-20'),
    dateOfBirth: new Date('1976-11-30'),
    location: 'Houston, TX',
    avatarColor: AVATAR_COLORS[3],
    isTopLevel: false,
    managerId: 'emp-001',
    emergencyContactName: 'Amaka Okafor',
    emergencyContactRelationship: 'Spouse',
    emergencyContactPhone: '+17135550499',
  },
  // ─── Level 2: Managers ───────────────────────────────────────────────────────
  {
    id: 'emp-005',
    employeeId: 'EMP-005',
    firstName: 'Aisha',
    lastName: 'Rahman',
    email: 'aisha.rahman@acme.com',
    phone: '+12125550505',
    jobTitle: 'Engineering Manager',
    department: Department.ENGINEERING,
    status: EmployeeStatus.ACTIVE,
    employmentType: EmploymentType.FULL_TIME,
    hireDate: new Date('2005-03-10'),
    dateOfBirth: new Date('1983-07-22'),
    location: 'New York, NY',
    avatarColor: AVATAR_COLORS[4],
    isTopLevel: false,
    managerId: 'emp-002',
    emergencyContactName: 'Karim Rahman',
    emergencyContactRelationship: 'Spouse',
    emergencyContactPhone: '+12125550599',
  },
  {
    id: 'emp-006',
    employeeId: 'EMP-006',
    firstName: 'Leo',
    lastName: 'Fernandez',
    email: 'leo.fernandez@acme.com',
    phone: '+13035550606',
    jobTitle: 'Senior Engineering Manager',
    department: Department.ENGINEERING,
    status: EmployeeStatus.ACTIVE,
    employmentType: EmploymentType.FULL_TIME,
    hireDate: new Date('2007-11-01'),
    dateOfBirth: new Date('1982-04-14'),
    location: 'Denver, CO',
    avatarColor: AVATAR_COLORS[5],
    isTopLevel: false,
    managerId: 'emp-002',
    emergencyContactName: 'Maria Fernandez',
    emergencyContactRelationship: 'Mother',
    emergencyContactPhone: '+13035550699',
  },
  {
    id: 'emp-007',
    employeeId: 'EMP-007',
    firstName: 'Claire',
    lastName: 'Dubois',
    email: 'claire.dubois@acme.com',
    phone: '+16175550707',
    jobTitle: 'Product Manager',
    department: Department.PRODUCT,
    status: EmployeeStatus.ACTIVE,
    employmentType: EmploymentType.FULL_TIME,
    hireDate: new Date('2008-06-15'),
    dateOfBirth: new Date('1985-01-03'),
    location: 'Boston, MA',
    avatarColor: AVATAR_COLORS[6],
    isTopLevel: false,
    managerId: 'emp-003',
    emergencyContactName: 'Pierre Dubois',
    emergencyContactRelationship: 'Father',
    emergencyContactPhone: '+16175550799',
  },
  {
    id: 'emp-008',
    employeeId: 'EMP-008',
    firstName: 'Ravi',
    lastName: 'Krishnamurthy',
    email: 'ravi.krishnamurthy@acme.com',
    phone: '+16505550808',
    jobTitle: 'HR Business Partner Lead',
    department: Department.HR,
    status: EmployeeStatus.ACTIVE,
    employmentType: EmploymentType.FULL_TIME,
    hireDate: new Date('2010-02-28'),
    dateOfBirth: new Date('1987-08-19'),
    location: 'Palo Alto, CA',
    avatarColor: AVATAR_COLORS[7],
    isTopLevel: false,
    managerId: 'emp-004',
    emergencyContactName: 'Priya Krishnamurthy',
    emergencyContactRelationship: 'Spouse',
    emergencyContactPhone: '+16505550899',
  },
  // ─── Level 3: Individual Contributors ────────────────────────────────────────
  {
    id: 'emp-009',
    employeeId: 'EMP-009',
    firstName: 'Jordan',
    lastName: 'Blake',
    email: 'jordan.blake@acme.com',
    phone: '+15105550909',
    jobTitle: 'Senior Software Engineer',
    department: Department.ENGINEERING,
    status: EmployeeStatus.ACTIVE,
    employmentType: EmploymentType.FULL_TIME,
    hireDate: new Date('2015-09-01'),
    dateOfBirth: new Date('1990-03-12'),
    location: 'Oakland, CA',
    avatarColor: AVATAR_COLORS[8],
    isTopLevel: false,
    managerId: 'emp-005',
    emergencyContactName: 'Taylor Blake',
    emergencyContactRelationship: 'Sibling',
    emergencyContactPhone: '+15105550999',
  },
  {
    id: 'emp-010',
    employeeId: 'EMP-010',
    firstName: 'Mei',
    lastName: 'Tanaka',
    email: 'mei.tanaka@acme.com',
    phone: '+14085551010',
    jobTitle: 'Software Engineer',
    department: Department.ENGINEERING,
    status: EmployeeStatus.ONBOARDING,
    employmentType: EmploymentType.FULL_TIME,
    hireDate: new Date('2026-07-15'),
    dateOfBirth: new Date('1995-05-28'),
    location: 'San Jose, CA',
    avatarColor: AVATAR_COLORS[9],
    isTopLevel: false,
    managerId: 'emp-005',
    emergencyContactName: 'Yuki Tanaka',
    emergencyContactRelationship: 'Mother',
    emergencyContactPhone: '+14085551099',
  },
  {
    id: 'emp-011',
    employeeId: 'EMP-011',
    firstName: 'Ethan',
    lastName: 'Morse',
    email: 'ethan.morse@acme.com',
    phone: '+13125551111',
    jobTitle: 'Staff Software Engineer',
    department: Department.ENGINEERING,
    status: EmployeeStatus.ACTIVE,
    employmentType: EmploymentType.FULL_TIME,
    hireDate: new Date('2012-04-01'),
    dateOfBirth: new Date('1988-12-07'),
    location: 'Chicago, IL',
    avatarColor: AVATAR_COLORS[0],
    isTopLevel: false,
    managerId: 'emp-006',
    emergencyContactName: 'Sarah Morse',
    emergencyContactRelationship: 'Spouse',
    emergencyContactPhone: '+13125551199',
  },
  {
    id: 'emp-012',
    employeeId: 'EMP-012',
    firstName: 'Nina',
    lastName: 'Kowalski',
    email: 'nina.kowalski@acme.com',
    phone: '+12065551212',
    jobTitle: 'DevOps Engineer',
    department: Department.ENGINEERING,
    status: EmployeeStatus.ON_LEAVE,
    employmentType: EmploymentType.FULL_TIME,
    hireDate: new Date('2016-01-11'),
    dateOfBirth: new Date('1991-09-25'),
    location: 'Seattle, WA',
    avatarColor: AVATAR_COLORS[1],
    isTopLevel: false,
    managerId: 'emp-006',
    emergencyContactName: 'Pavel Kowalski',
    emergencyContactRelationship: 'Father',
    emergencyContactPhone: '+12065551299',
  },
  {
    id: 'emp-013',
    employeeId: 'EMP-013',
    firstName: 'Amara',
    lastName: 'Diallo',
    email: 'amara.diallo@acme.com',
    phone: '+14045551313',
    jobTitle: 'Product Analyst',
    department: Department.PRODUCT,
    status: EmployeeStatus.ACTIVE,
    employmentType: EmploymentType.FULL_TIME,
    hireDate: new Date('2018-11-05'),
    dateOfBirth: new Date('1993-06-17'),
    location: 'Atlanta, GA',
    avatarColor: AVATAR_COLORS[2],
    isTopLevel: false,
    managerId: 'emp-007',
    emergencyContactName: 'Ibrahim Diallo',
    emergencyContactRelationship: 'Father',
    emergencyContactPhone: '+14045551399',
  },
  {
    id: 'emp-014',
    employeeId: 'EMP-014',
    firstName: 'Carlos',
    lastName: 'Vega',
    email: 'carlos.vega@acme.com',
    phone: '+17025551414',
    jobTitle: 'UX Researcher',
    department: Department.DESIGN,
    status: EmployeeStatus.ACTIVE,
    employmentType: EmploymentType.CONTRACT,
    hireDate: new Date('2020-03-16'),
    dateOfBirth: new Date('1989-11-04'),
    location: 'Las Vegas, NV',
    avatarColor: AVATAR_COLORS[3],
    isTopLevel: false,
    managerId: 'emp-007',
    emergencyContactName: 'Rosa Vega',
    emergencyContactRelationship: 'Mother',
    emergencyContactPhone: '+17025551499',
  },
  {
    id: 'emp-015',
    employeeId: 'EMP-015',
    firstName: 'Priya',
    lastName: 'Nair',
    email: 'priya.nair@acme.com',
    phone: '+16025551515',
    jobTitle: 'HR Coordinator',
    department: Department.HR,
    status: EmployeeStatus.ACTIVE,
    employmentType: EmploymentType.FULL_TIME,
    hireDate: new Date('2019-07-22'),
    dateOfBirth: new Date('1994-02-28'),
    location: 'Phoenix, AZ',
    avatarColor: AVATAR_COLORS[4],
    isTopLevel: false,
    managerId: 'emp-008',
    emergencyContactName: 'Suresh Nair',
    emergencyContactRelationship: 'Father',
    emergencyContactPhone: '+16025551599',
  },
  {
    id: 'emp-016',
    employeeId: 'EMP-016',
    firstName: 'Owen',
    lastName: 'MacAllister',
    email: 'owen.macallister@acme.com',
    phone: '+16125551616',
    jobTitle: 'Talent Acquisition Specialist',
    department: Department.HR,
    status: EmployeeStatus.ACTIVE,
    employmentType: EmploymentType.FULL_TIME,
    hireDate: new Date('2021-02-01'),
    dateOfBirth: new Date('1996-07-09'),
    location: 'Minneapolis, MN',
    avatarColor: AVATAR_COLORS[5],
    isTopLevel: false,
    managerId: 'emp-008',
    emergencyContactName: 'Fiona MacAllister',
    emergencyContactRelationship: 'Mother',
    emergencyContactPhone: '+16125551699',
  },
  {
    id: 'emp-017',
    employeeId: 'EMP-017',
    firstName: 'Zoe',
    lastName: 'Nakamura',
    email: 'zoe.nakamura@acme.com',
    phone: '+18085551717',
    jobTitle: 'Full Stack Engineer',
    department: Department.ENGINEERING,
    status: EmployeeStatus.ACTIVE,
    employmentType: EmploymentType.FULL_TIME,
    hireDate: new Date('2022-09-06'),
    dateOfBirth: new Date('1997-04-15'),
    location: 'Honolulu, HI',
    avatarColor: AVATAR_COLORS[6],
    isTopLevel: false,
    managerId: 'emp-005',
    emergencyContactName: 'Kenji Nakamura',
    emergencyContactRelationship: 'Father',
    emergencyContactPhone: '+18085551799',
  },
  {
    id: 'emp-018',
    employeeId: 'EMP-018',
    firstName: 'Felix',
    lastName: 'Bergstrom',
    email: 'felix.bergstrom@acme.com',
    phone: '+13035551818',
    jobTitle: 'Senior Product Manager',
    department: Department.PRODUCT,
    status: EmployeeStatus.ONBOARDING,
    employmentType: EmploymentType.FULL_TIME,
    hireDate: new Date('2026-08-01'),
    dateOfBirth: new Date('1988-03-22'),
    location: 'Denver, CO',
    avatarColor: AVATAR_COLORS[7],
    isTopLevel: false,
    managerId: 'emp-003',
    emergencyContactName: 'Ingrid Bergstrom',
    emergencyContactRelationship: 'Spouse',
    emergencyContactPhone: '+13035551899',
  },
];

async function main() {
  console.log('🌱 Starting seed...');
  await prisma.employee.deleteMany();
  console.log('🗑️  Cleared existing employees');

  for (const emp of employees) {
    await prisma.employee.create({ data: emp });
    process.stdout.write('.');
  }

  console.log(`\n✅ Seeded ${employees.length} employees`);
}

main()
  .catch((e) => {
    console.error('❌ Seed failed:', e);
    process.exit(1);
  })
  .finally(async () => {
    await prisma.$disconnect();
  });
